# Generated by Django 2.2 on 2019-04-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendingMachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beveragelist',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
